title: Marc A Hester
email: marc@hester.be
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://marc.hester.be"
twitter_username: maercoftheshire
github_username:  maercoftheshire

# Build settings
markdown: kramdown
